### ISSUE TITLE
Code needs documentation

### ISSUE THREAD

**Issue by luisortizuriarte** [nTavakoli/Assignment3_new#2]
As you write your code, keep in mind to document what you are doing. This will help other people (like me!) understand what you are doing and how to offer help, and it will help future you understand what you wrote!

Please add documentation to your code using markdown cells and inline comments so that a reader can understand your code.

**Comment by nTavakoli** [comment]
I added documentation as well as inline comments in my code.

**Comment by luisortizuriarte** [comment]
The documentation of your code is much better now. Thanks! Closing issue.
