### ISSUE TITLE
Defining your index phase

### ISSUE THREAD

**Issue by luisortizuriarte** [nTavakoli/Assignment3_new#3]
In your data, you chose neutral conditions be represented when SOI= 0. However, this is a very strict requirement (the probability of SOI being a specific number is going to be very low) so you end up with very low number of neutral years. If you filtered your NAO index to include other small values like we did with ENSO, you might have a more balanced distribution.

**Comment by luisortizuriarte** [comment]
This may not be an issue if you're only interested in looking at positive vs negative values of SOI!

**Comment by nTavakoli** [comment]
To solve this problem, I  calculated 15 and 85 percentages of SOI to determine a threshold for El Nino, La Nino, and Neutral phases. The 15 % of lower and higher percentages of SOI have been considered as El Nino and La Nino, respectively. Neutral is considered between these two thresholds.

**Comment by luisortizuriarte** [comment]
Your solution solves this issue by having a range for SOI. I'll close this issue.
