### ISSUE TITLE
Subsetting with .sel

### ISSUE THREAD

**Issue by luisortizuriarte** [nTavakoli/Assignment3_new#4]
You might want to double check that the time coordinates in your index doesn't exceed the time coordinate in your soil moisture data, which is a common reason you see the error in In[18]

`KeyError: "not all values found in index 'time'"`

**Comment by nTavakoli** [comment]
The main problem that I had here was the digit of time coordinates in my index and data did not match, because of that the same time coordinates could not be found. Therefore, I substituted both time dimensions with string and defined a new time. Now, this problem has been solved.

**Comment by luisortizuriarte** [comment]
Your issue with .sel is solved. Closing this issue.
